**Name:** @itscroknight


---



**Practical 1:**
Data Wrangling, I
Perform the following operations using Python on any open source dataset (e.g., data.csv)


1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide
a clear description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas dataframe.
4. Data Preprocessing: check for missing values in the data using pandas isnull(),
describe() function to get some initial statistics. Provide variable descriptions. Types
of variables etc. Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by
checking the data types (i.e., character, numeric, integer, factor, and logical) of the
variables in the data set. If variables are not in the correct data type, apply proper
type conversions.
6. Turn categorical variables into quantitative variables in Python.

Importing Pandas and NumPy Library.

In [ ]:
import pandas as pd
import numpy as np

Reading data using pd.read_csv command

In [ ]:
df = pd.read_csv('/content/nba.csv')

In [ ]:
df

,NaNme,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,2-Jun,180,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25,6-Jun,235,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27,5-Jun,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,5-Jun,185,Georgia State,1148640
4,JoNaNs Jerebko,Boston Celtics,8,PF,29,10-Jun,231,NaN,5000000
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,10-Jun,234,Kentucky,2239800
453,Shelvin Mack,Utah Jazz,8,PG,26,3-Jun,203,Butler,2433333
454,Raul Neto,Utah Jazz,25,PG,24,1-Jun,179,NaN,900000
455,Tibor Pleiss,Utah Jazz,21,C,26,3-Jul,256,NaN,2900000
456,Jeff Withey,Utah Jazz,24,C,26,Jul-00,231,Kansas,947276

The describe() function gives basic statistics about the data.

In [ ]:
df.describe()

           Number         Age      Weight
count  457.000000  457.000000  457.000000
mean    17.678337   26.938731  221.522976
std     15.966090    4.404016   26.368343
min      0.000000   19.000000  161.000000
25%      5.000000   24.000000  200.000000
50%     13.000000   26.000000  220.000000
75%     25.000000   30.000000  240.000000
max     99.000000   40.000000  307.000000

Displays info about each column.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NaNme     457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    int64
 3   Position  457 non-null    object
 4   Age       457 non-null    int64
 5   Height    457 non-null    object
 6   Weight    457 non-null    int64
 7   College   373 non-null    object
 8   Salary    447 non-null    object
dtypes: int64(3), object(6)
memory usage: 32.3+ KB

Checking for null values.

In [ ]:
df.isnull()

     NaNme   Team  Number  Position    Age  Height  Weight  College  Salary
0    False  False   False     False  False   False   False    False   False
1    False  False   False     False  False   False   False    False   False
2    False  False   False     False  False   False   False    False    True
3    False  False   False     False  False   False   False    False   False
4    False  False   False     False  False   False   False     True   False
..     ...    ...     ...       ...    ...     ...     ...      ...     ...
452  False  False   False     False  False   False   False    False   False
453  False  False   False     False  False   False   False    False   False
454  False  False   False     False  False   False   False     True   False
455  False  False   False     False  False   False   False     True   False
456  False  False   False     False  False   False   False    False   False

[457 rows x 9 columns]

In [ ]:
df.isnull().any()

NaNme       False
Team        False
Number      False
Position    False
Age         False
Height      False
Weight      False
College      True
Salary       True
dtype: bool

Dispalys the total null values in each column.

In [ ]:
df.isna().sum()

NaNme        0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      10
dtype: int64

Displays first 5 values.

In [ ]:
df.head()

,NaNme,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,2-Jun,180,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25,6-Jun,235,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27,5-Jun,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,5-Jun,185,Georgia State,1148640
4,JoNaNs Jerebko,Boston Celtics,8,PF,29,10-Jun,231,NaN,5000000

In [ ]:
df.tail()

,NaNme,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41,PF,20,10-Jun,234,Kentucky,2239800
453,Shelvin Mack,Utah Jazz,8,PG,26,3-Jun,203,Butler,2433333
454,Raul Neto,Utah Jazz,25,PG,24,1-Jun,179,NaN,900000
455,Tibor Pleiss,Utah Jazz,21,C,26,3-Jul,256,NaN,2900000
456,Jeff Withey,Utah Jazz,24,C,26,Jul-00,231,Kansas,947276

Applying Formatting to the data:

Changing font color to red.

In [ ]:
df.head(10).style.set_properties(**{'color':'red'})

Changing Backgound Color: To yellow and font color to red

In [ ]:
df.head(10).style.set_properties(**{'background-color': 'yellow', 'color': 'red'})

In [ ]:
import sklearn
from sklearn import preprocessing

Drops the rows containg null values.

In [ ]:
df.dropna(axis =0, inplace=True)

Seperating Quantitative Columns and storing it in df1

In [ ]:
df1 = df[['Age', 'Salary']]

In [ ]:
df1

     Age   Salary
0     25  7730337
1     25  6796117
3     22  1148640
6     21  1170960
7     25  2165160
..   ...      ...
449   23  1348440
451   26   981348
452   20  2239800
453   26  2433333
456   26   947276

[365 rows x 2 columns]

Using Min-Max-Scaler to preprocess the data:

In [ ]:
min_max_scalar = preprocessing.MinMaxScaler()

In [ ]:
df1_scaled = min_max_scalar.fit_transform(df1)

In [ ]:
df1.replace('NaNN', 0, inplace =True)

In [ ]:
df1_scaled

array([[0.28571429, 0.33793823],
       [0.28571429, 0.29709801],
       [0.14285714, 0.05021377],
       [0.0952381 , 0.05118951],
       [0.28571429, 0.0946518 ],
       [0.14285714, 0.07975344],
       [0.14285714, 0.14999082],
       [0.23809524, 0.11231738],
       [0.38095238, 0.30220192],
       [0.38095238, 0.14974907],
       [0.04761905, 0.07649574],
       [0.33333333, 0.11440328],
       [0.23809524, 0.03694247],
       [0.42857143, 0.06557377],
       [0.0952381 , 0.05838164],
       [0.61904762, 0.27540984],
       [0.33333333, 0.00586732],
       [0.19047619, 0.06557377],
       [0.42857143, 0.86072131],
       [0.0952381 , 0.04984656],
       [0.33333333, 0.04141097],
       [0.28571429, 0.04290046],
       [0.33333333, 0.04141097],
       [0.42857143, 0.04141097],
       [0.38095238, 0.49118929],
       [0.52380952, 0.34972678],
       [0.66666667, 0.07149622],
       [0.61904762, 1.        ],
       [0.28571429, 0.03694247],
       [0.23809524, 0.03694247],
       [0.19047619, 0.06873705],
       [0.42857143, 0.55300546],
       [0.33333333, 0.16393443],
       [0.42857143, 0.07155593],
       [0.28571429, 0.17486339],
       [0.19047619, 0.0073183 ],
       [0.85714286, 0.        ],
       [0.28571429, 0.04141097],
       [0.28571429, 0.04371585],
       [0.14285714, 0.20227148],
       [0.14285714, 0.03694247],
       [0.14285714, 0.04695821],
       [0.61904762, 0.28415301],
       [0.23809524, 0.09376052],
       [0.23809524, 0.02295489],
       [0.14285714, 0.15116066],
       [0.04761905, 0.20033574],
       [0.38095238, 0.04141097],
       [0.14285714, 0.12544   ],
       [0.28571429, 0.04141097],
       [0.04761905, 0.02295489],
       [0.47619048, 0.59453552],
       [0.33333333, 0.43934426],
       [0.47619048, 0.10928962],
       [0.23809524, 0.30601093],
       [0.52380952, 0.52459016],
       [0.38095238, 0.27404044],
       [0.19047619, 0.0284153 ],
       [0.28571429, 0.15536249],
       [0.47619048, 0.01071812],
       [0.23809524, 0.06598295],
       [0.23809524, 0.16932887],
       [0.57142857, 0.60327869],
       [0.28571429, 0.04141097],
       [0.42857143, 0.49708354],
       [0.33333333, 0.08781412],
       [0.33333333, 0.62342601],
       [0.61904762, 0.5119325 ],
       [0.04761905, 0.04948459],
       [0.19047619, 0.03694247],
       [0.52380952, 0.05556127],
       [0.42857143, 0.16677596],
       [0.33333333, 0.67763934],
       [0.38095238, 0.04811375],
       [0.47619048, 0.00487187],
       [0.80952381, 0.24808743],
       [0.19047619, 0.02295489],
       [0.47619048, 0.42185792],
       [0.38095238, 0.82656726],
       [0.42857143, 0.04811375],
       [0.38095238, 0.86072131],
       [0.47619048, 0.04141097],
       [0.57142857, 0.93852219],
       [0.9047619 , 0.1475847 ],
       [0.57142857, 0.30972678],
       [0.19047619, 0.13599108],
       [0.28571429, 0.05069639],
       [0.57142857, 0.13114754],
       [0.23809524, 0.03694247],
       [0.19047619, 0.03060109],
       [0.23809524, 0.03694247],
       [0.47619048, 0.68162697],
       [0.28571429, 0.07537705],
       [0.19047619, 0.05051803],
       [0.0952381 , 0.13692852],
       [0.04761905, 0.22308721],
       [0.38095238, 0.04290046],
       [0.80952381, 0.04141097],
       [0.57142857, 0.22816039],
       [0.33333333, 0.59016393],
       [0.        , 0.09302033],
       [0.42857143, 0.00901386],
       [0.0952381 , 0.05071738],
       [0.28571429, 0.04290046],
       [0.23809524, 0.59016393],
       [0.14285714, 0.16643148],
       [0.38095238, 0.0452459 ],
       [0.28571429, 0.00243593],
       [0.61904762, 0.04141097],
       [0.57142857, 0.24043716],
       [0.14285714, 0.08922754],
       [0.19047619, 0.00364577],
       [0.28571429, 0.04290046],
       [0.38095238, 0.04438999],
       [0.80952381, 0.06335244],
       [0.14285714, 0.14855869],
       [0.42857143, 0.21917198],
       [0.28571429, 0.69298142],
       [0.28571429, 0.04141097],
       [0.23809524, 0.02295489],
       [0.47619048, 0.54221207],
       [0.38095238, 0.33661202],
       [0.19047619, 0.13799344],
       [0.23809524, 0.03694247],
       [0.52380952, 0.41530055],
       [0.28571429, 0.03694247],
       [0.57142857, 0.09836066],
       [0.33333333, 0.71726776],
       [0.76190476, 0.19672131],
       [0.52380952, 0.3715847 ],
       [0.38095238, 0.04141097],
       [0.23809524, 0.10406295],
       [0.38095238, 0.04438999],
       [0.57142857, 0.58579235],
       [0.0952381 , 0.06081574],
       [0.38095238, 0.87838531],
       [0.23809524, 0.0671423 ],
       [0.28571429, 0.05015414],
       [0.66666667, 0.3581652 ],
       [0.23809524, 0.7172678 ],
       [0.76190476, 0.04141097],
       [0.76190476, 0.04141097],
       [0.57142857, 0.05578142],
       [0.38095238, 0.86072131],
       [0.28571429, 0.00486103],
       [0.28571429, 0.39295148],
       [0.28571429, 0.62342601],
       [0.66666667, 0.09180328],
       [0.66666667, 0.10928962],
       [0.47619048, 0.28415301],
       [0.80952381, 0.09488372],
       [0.28571429, 0.00487187],
       [0.28571429, 0.05475148],
       [0.19047619, 0.12641574],
       [0.19047619, 0.03694247],
       [0.14285714, 0.14304223],
       [0.19047619, 0.69945355],
       [0.19047619, 0.02622951],
       [0.33333333, 0.6082205 ],
       [0.04761905, 0.12423869],
       [0.42857143, 0.27409836],
       [0.33333333, 0.21857923],
       [0.57142857, 0.13114754],
       [0.38095238, 0.17704918],
       [0.23809524, 0.04402299],
       [0.33333333, 0.74841993],
       [0.52380952, 0.34972678],
       [0.42857143, 0.17486339],
       [0.28571429, 0.05940459],
       [0.42857143, 0.00925657],
       [0.14285714, 0.04808743],
       [0.52380952, 0.30601093],
       [0.04761905, 0.10307148],
       [0.28571429, 0.03694247],
       [0.19047619, 0.04402299],
       [0.38095238, 0.13114754],
       [0.23809524, 0.10487607],
       [0.28571429, 0.04141097],
       [0.0952381 , 0.07267148],
       [0.28571429, 0.1286654 ],
       [0.42857143, 0.34972678],
       [0.23809524, 0.64262295],
       [0.33333333, 0.71726776],
       [0.61904762, 0.01291047],
       [0.19047619, 0.03694247],
       [0.0952381 , 0.22524328],
       [0.38095238, 0.09220957],
       [0.47619048, 0.28852459],
       [0.        , 0.07576131],
       [0.14285714, 0.06334426],
       [0.57142857, 0.18754098],
       [0.42857143, 0.04811375],
       [0.57142857, 0.17269128],
       [0.66666667, 0.17719983],
       [0.66666667, 0.09117687],
       [0.47619048, 0.71726776],
       [0.42857143, 0.05556127],
       [0.38095238, 0.67154098],
       [0.23809524, 0.03694247],
       [0.57142857, 0.04141097],
       [0.57142857, 0.2351464 ],
       [0.52380952, 0.35816525],
       [0.38095238, 0.01340009],
       [0.38095238, 0.28356223],
       [0.52380952, 0.3597541 ],
       [0.14285714, 0.07197377],
       [0.38095238, 0.0087694 ],
       [0.33333333, 0.68880603],
       [0.14285714, 0.04371585],
       [0.23809524, 0.10883191],
       [0.19047619, 0.13944455],
       [0.9047619 , 0.04141097],
       [0.0952381 , 0.06140328],
       [0.71428571, 0.2255099 ],
       [0.85714286, 0.21857923],
       [0.80952381, 0.15486339],
       [0.95238095, 0.17871121],
       [0.42857143, 0.41916616],
       [0.19047619, 0.03064052],
       [0.28571429, 0.03694247],
       [0.19047619, 0.05252197],
       [0.14285714, 0.05380721],
       [0.71428571, 0.4213576 ],
       [0.28571429, 0.39344262],
       [0.42857143, 0.23886339],
       [0.42857143, 0.3715847 ],
       [0.33333333, 0.04811375],
       [0.38095238, 0.13276184],
       [0.47619048, 0.12459016],
       [0.19047619, 0.30910295],
       [0.19047619, 0.00742658],
       [0.52380952, 0.05092275],
       [0.28571429, 0.03694247],
       [0.33333333, 0.46927152],
       [0.28571429, 0.03694247],
       [0.47619048, 0.05770492],
       [0.38095238, 0.67820901],
       [0.28571429, 0.04438999],
       [0.28571429, 0.46319156],
       [0.38095238, 0.00243593],
       [0.42857143, 0.147848  ],
       [0.52380952, 0.86072131],
       [0.14285714, 0.04996197],
       [0.80952381, 0.04141097],
       [1.        , 0.2295082 ],
       [0.42857143, 0.43715847],
       [0.23809524, 0.71726776],
       [0.66666667, 0.0087694 ],
       [1.        , 0.01096175],
       [0.38095238, 0.1564567 ],
       [0.33333333, 0.02295489],
       [0.76190476, 0.06553823],
       [0.33333333, 0.08743169],
       [0.23809524, 0.0570282 ],
       [0.76190476, 0.12480612],
       [0.52380952, 0.52459016],
       [0.57142857, 0.04371585],
       [0.76190476, 0.2512122 ],
       [0.57142857, 0.81624739],
       [0.23809524, 0.04141097],
       [0.23809524, 0.02295489],
       [0.38095238, 0.14571948],
       [0.38095238, 0.34972678],
       [0.23809524, 0.04141097],
       [0.38095238, 0.00828219],
       [0.52380952, 0.04141097],
       [0.0952381 , 0.02295489],
       [0.42857143, 0.26710531],
       [0.19047619, 0.11420852],
       [0.14285714, 0.27678269],
       [0.23809524, 0.13264944],
       [0.52380952, 0.24808743],
       [0.38095238, 0.0935082 ],
       [0.33333333, 0.52459016],
       [0.47619048, 0.30601093],
       [0.19047619, 0.18379016],
       [0.61904762, 0.97017399],
       [0.57142857, 0.44378632],
       [0.80952381, 0.12480612],
       [0.71428571, 0.01144892],
       [0.23809524, 0.03694247],
       [0.47619048, 0.24234863],
       [0.14285714, 0.02295489],
       [0.71428571, 0.87431694],
       [0.33333333, 0.04290046],
       [0.04761905, 0.10849049],
       [0.33333333, 0.04141097],
       [0.04761905, 0.18236852],
       [0.19047619, 0.03694247],
       [0.23809524, 0.05658754],
       [0.33333333, 0.10406964],
       [0.23809524, 0.22699541],
       [0.14285714, 0.10953967],
       [0.52380952, 0.18797814],
       [0.28571429, 0.49180328],
       [0.61904762, 0.21857923],
       [0.66666667, 0.17486339],
       [0.14285714, 0.2489475 ],
       [0.52380952, 0.19125683],
       [0.23809524, 0.02455589],
       [0.71428571, 0.1442623 ],
       [0.38095238, 0.01193609],
       [0.33333333, 0.34972678],
       [0.04761905, 0.08394492],
       [0.19047619, 0.20384525],
       [0.52380952, 0.09488372],
       [0.52380952, 0.04811375],
       [0.47619048, 0.0087694 ],
       [0.28571429, 0.69298142],
       [0.42857143, 0.12301639],
       [0.42857143, 0.13114754],
       [0.28571429, 0.15446264],
       [0.47619048, 0.45680603],
       [0.33333333, 0.49118929],
       [0.0952381 , 0.06926689],
       [0.80952381, 0.04141097],
       [0.71428571, 0.18994536],
       [0.19047619, 0.01130007],
       [0.33333333, 0.06445639],
       [0.04761905, 0.05604721],
       [0.0952381 , 0.09391738],
       [0.19047619, 0.08992   ],
       [0.28571429, 0.08475803],
       [0.80952381, 0.04141097],
       [0.04761905, 0.2493377 ],
       [0.0952381 , 0.25174557],
       [0.14285714, 0.09963016],
       [0.76190476, 0.16393443],
       [0.38095238, 0.88125123],
       [0.61904762, 0.13704918],
       [0.23809524, 0.04984656],
       [0.23809524, 0.71726776],
       [0.23809524, 0.06395803],
       [0.9047619 , 0.00974374],
       [0.52380952, 0.14618579],
       [0.0952381 , 0.08837246],
       [0.23809524, 0.05293115],
       [0.42857143, 0.19672131],
       [0.23809524, 0.22463082],
       [0.38095238, 0.73198767],
       [0.04761905, 0.02295489],
       [0.28571429, 0.35160197],
       [0.19047619, 0.02732647],
       [0.23809524, 0.04141097],
       [0.38095238, 0.30517167],
       [0.19047619, 0.12651624],
       [0.42857143, 0.26229508],
       [0.71428571, 0.21927869],
       [0.23809524, 0.1344647 ],
       [0.28571429, 0.18519287],
       [0.23809524, 0.11038951],
       [0.19047619, 0.02295489],
       [0.33333333, 0.06188066],
       [0.52380952, 0.12480612],
       [0.04761905, 0.11531016],
       [0.42857143, 0.20874317],
       [0.19047619, 0.11620721],
       [0.23809524, 0.41370422],
       [0.23809524, 0.52459016],
       [0.33333333, 0.6736424 ],
       [0.19047619, 0.0589482 ],
       [0.33333333, 0.04290046],
       [0.04761905, 0.09791475],
       [0.33333333, 0.10637521],
       [0.33333333, 0.04141097]])

Using Label Encoding to encode the column "Position"

In [ ]:
label_encoding = preprocessing.LabelEncoder()

In [ ]:
df['Position'] = label_encoding.fit_transform(df['Position'])

In [ ]:
df['Position'].unique()

array([2, 3, 4, 1, 0])

In [ ]:
df

,NaNme,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,2,25,2-Jun,180,Texas,7730337
1,Jae Crowder,Boston Celtics,99,3,25,6-Jun,235,Marquette,6796117
3,R.J. Hunter,Boston Celtics,28,4,22,5-Jun,185,Georgia State,1148640
6,Jordan Mickey,Boston Celtics,55,1,21,8-Jun,235,LSU,1170960
7,Kelly Olynyk,Boston Celtics,41,0,25,Jul-00,238,Gonzaga,2165160
...,...,...,...,...,...,...,...,...,...
449,Rodney Hood,Utah Jazz,5,4,23,8-Jun,206,Duke,1348440
451,Chris Johnson,Utah Jazz,23,3,26,6-Jun,206,Dayton,981348
452,Trey Lyles,Utah Jazz,41,1,20,10-Jun,234,Kentucky,2239800
453,Shelvin Mack,Utah Jazz,8,2,26,3-Jun,203,Butler,2433333
456,Jeff Withey,Utah Jazz,24,0,26,Jul-00,231,Kansas,947276